In [59]:
import numpy as np
np.array([range(i, i + 4) for i in [11, 15]])


array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [60]:
import numpy as np
np.array([[0,0,0], [0,0,0], [0,0,0], [0,0,0]] , dtype='float32')
          

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [61]:
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
import numpy as np
np.array([range(i, i + 10) for i in [4]])


array([[ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [63]:
import numpy as np
np.array([[0., 1.5, 3.0, 4.5]])

array([[0. , 1.5, 3. , 4.5]])

In [64]:
import numpy as np
np.array ([[4,4],[4,4]])

array([[4, 4],
       [4, 4]])

In [65]:
import numpy as np 
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [66]:
import numpy as np
x = np.array ([10,12])
np.diag(x)

array([[10,  0],
       [ 0, 12]])

In [67]:
import numpy as np
10*np.random.random_sample((3, 3))

array([[2.59744171, 5.13047028, 3.99792859],
       [4.28299253, 4.67651836, 6.52302833],
       [6.61257061, 5.41535907, 2.0408885 ]])

In [68]:
import numpy as np
np.random.random_integers(10, high = 20, size=(3,3))


C:\Users\USER\AppData\Local\Temp\ipykernel_7624\627953021.py:2: DeprecationWarning: This function is deprecated. Please call randint(10, 20 + 1) instead
  np.random.random_integers(10, high = 20, size=(3,3))


array([[15, 16, 19],
       [12, 19, 20],
       [13, 18, 20]])

In [74]:
import numpy as np
myArray= np.array([[11,12,13], [14,15,16], [17,18,19]])
myArray[:1 , :2]

array([[11, 12]])

In [77]:
import numpy as np
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
myArray[:2, :] = 0
print (myArray)

[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


In [85]:
import numpy as np
x = np.array([range(i, i + 21) for i in [0]])
x_reversed = x[:,::-1]
print(x_reversed)

[[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]]


In [86]:
import numpy as np
myArray = np.array([[11,12,13], [14,15,16]])
myArray.reshape(3,2)


array([[11, 12],
       [13, 14],
       [15, 16]])

In [87]:
import numpy as np
myArray = np.arange(10)
np.power(myArray, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [89]:
import numpy as np
myArray = np.arange(10)
np.sqrt(myArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [91]:
import numpy as np
myArray = np.arange(10)
squared = np.power(myArray, 2)
root = np.sqrt(myArray)
result = squared * root
print(result)

[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


In [92]:
import numpy as np
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
print(myArray)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [98]:
import numpy as np
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
newRow = np.array([[20,21,22]])
y = np.vstack((myArray, newRow))

                    

[[11 12 13 30]
 [14 15 16 40]
 [17 18 19 50]] [[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [100]:
import numpy as np
newColumn = np.array([[30], [40] ,[50]])
x = np.hstack((myArray, newColumn))
print(x)


[[11 12 13 30]
 [14 15 16 40]
 [17 18 19 50]]


In [111]:
import numpy as np
myArray = np.zeros((2,2))
newC = np.ones((2,1))
z = np.hstack((myArray, newC))
print(z)

[[0. 0. 1.]
 [0. 0. 1.]]


In [124]:
import numpy as np
zeros_rows = np.zeros((2,3))
final_array = np.vstack((z,zeros_rows))
print(final_array)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [125]:
import numpy as np
final_array_without_last_column = np.delete(final_array, -1, axis=1)
print(final_array_without_last_column)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [126]:
import numpy as np
final_array_without_last_row = np.delete(final_array_without_last_column, -1, axis=0)
print(final_array_without_last_row)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [134]:
import numpy as np
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
column_to_remove = 1
result_array = np.delete(myArray, column_to_remove, axis=1)
print(result_array)

[[1 3]
 [4 6]
 [9 7]]


In [135]:
import numpy as np
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
mask = exercise_1 % 2 != 0
exercise_1[mask] = -1
print(exercise_1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [136]:
import numpy as np
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
result = np.reshape(exercise_2, (3, -1))
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [137]:
import numpy as np
exercise_3 = np.arange(4).reshape(2, -1)
result = exercise_3 + 202
print(result)

[[202 203]
 [204 205]]


In [138]:
import numpy as np
random_array = np.random.randint(30, 41, size=10)
print(random_array)

[39 34 30 36 38 32 38 36 36 32]


In [139]:
import numpy as np
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
positions_gt = np.where(x > y)
positions_eq = np.where(x == y)
print(positions_gt, positions_eq)

(array([1, 2, 4, 5, 6, 7, 8, 9], dtype=int64),) (array([0], dtype=int64),)


In [140]:
import numpy as np
exercise_6 = np.arange(100).reshape(5, -1)
first_four_columns = exercise_6[:, :4]
print(first_four_columns)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
